let WIDTH
let HEIGHT
let DEPTH

let NUM_BEES = 1
let NUM_FOODS = 80

let LIFE_BEE = 1500
let LIFE_FOOD = 10

let STORED_FOOD = 0
let NEW_BEE_COST = 1

let VEL_LIMIT = 8 // limit of velocity
let SEP_MULTIPLIER = 0.07
let ALI_MULTIPLIER = 0.07
let COH_MULTIPLIER = 0.07
let SEN_MULTIPLIER = 0.1
let WAN_MULTIPLIER = 0.25
let ATK_MULTIPLIER = 0.8

let PRE_COH_MULTIPLIER = 0.5

let NEIGHBOR_DIST = 100
let NEIGHBOR_ANGLE = 120
let SENSE_DIST = 200
let CHECK_DIST = 20
let ATK_DIST = 1500

let ATTACKER = 0
let COLLECTOR = 1

let env;
